# Generated by Django 4.2.4 on 2023-10-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_app', '0002_signup_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('option', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='MyNotes')),
                ('comment', models.TextField()),
            ],
        ),
    ]
